name: cron job demo
run-name: demo the cron job using github actions

on: push
  # schedule:
  #   - cron: '* * * *'

jobs:
  Cron-Job-Demo:
    name: demo the cron job
    runs-on: ubuntu-latest
    
    steps:
      - name: running echo cmd
        run: echo $HOME
      
      - run: mkdir demo_file
      - run: ls